### ISSUE TITLE
Wrong encoder used in resnet101dilated config file

### ISSUE THREAD

**Issue by liu115** [CSAILVision/semantic-segmentation-pytorch#215]
In `config/ade20k-resnet101dilated-ppm_deepsup.yaml`, the part define the encoder is
```
MODEL:
  arch_encoder: "resnet50dilated"
  arch_decoder: "ppm_deepsup"
  fc_dim: 2048
```
Shouldn't it be resnet101dilated? Thanks.
